trigger:
  - azure-pipeline
pool:
  vmImage: 'ubuntu-latest'
stages:
  - stage: Build
    jobs:
      - job:
        displayName: Build and Run Tests
        steps:
          - task: DockerCompose@0
            displayName: Build SeleniumGrid
            inputs:
              containerregistrytype: Container Registry
              dockerComposeFile: docker-compose.yml
              dockerComposeCommand: 'up -d'
          - task: SonarQubePrepare@5
            inputs:
              SonarQube: 'sonarqube'
              scannerMode: 'CLI'
              configMode: 'file'
              configFile: 'sonar-scanner.properties'
              extraProperties: 'sonar.projectKey=JavaProjectDemo'
          - powershell: |
              $params = "$env:SONARQUBE_SCANNER_PARAMS" -replace '"sonar.branch.name":"[\w/,-.]*"\,?'
              Write-Host "##vso[task.setvariable variable=SONARQUBE_SCANNER_PARAMS]$params"
            displayName: Set SonarScanner Params
          - task: Maven@3
            displayName: Run Tests
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'test'
              options: 'clean test -Dsurefire.suiteXmLFiles=regression.xml'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
              sqMavenPluginVersionChoice: 'latest'
          - task: SonarQubeAnalyze@4
          - task: SonarQubePublish@5
            inputs:
              pollingTimeoutSec: '300'
          - task: SendGrid@1
            inputs:
              sendgridkey: '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'
              to: 'exthung.sang@bcg.com'
              from: 'exthung.sang@bcg.com'
              subject: 'Test Result Report'
              htmlbody: 
              addattachment: true
              attachment: '**/surefire-reports/*.html'