name: CICD Demo
on:
  push:
  pull_request:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build Docker Env
        run: docker-compose up -d
      - name: Run Tests
        run: mvn clean test -Dsurefire.suiteXmlFiles=regression.xml
